import React, { useEffect, useState } from 'react';
import axios from 'axios';
import req from './req';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';

// base url to append with the image title so we can get the movie poster 
const parent_url = "https://image.tmdb.org/t/p/original/";

const Banner = () => {
    // create a State Hook to store movies information.
    const [movies, setMovies] = useState([]);

    useEffect(() => {
        async function fetchMedia() {
            // request to API
            const request = await axios.get(req.pullTrending);
            // request movie by id of the random number generated by the math operation
            setMovies(request.data.results[Math.floor(Math.random() * request.data.results.length - 1)]);

            return request;
        }
        // call function to execute
        fetchMedia();
    }, [])

    // truncate function which cuts movies with excessive words.
    function cutshort(str, c){
        return str?.length > c ? str.substr(0, c - 1) + "..." : str;
    }

  return (
    <>
        {/** create inline styling to set banner image. */}
        <section className='banner' style={{
            backgroundSize: "cover",
            backgroundImage: `url(${parent_url}${movies?.backdrop_path})`,
            backgroundPosition: "center center"
        }}>
            <div className="banner_details">
                {/* get title, name OR original name attribute from API depending on what the API used to save movie title */}
                <h2>{cutshort(movies?.title, 24) || cutshort(movies?.name, 24) || cutshort(movies?.original_name, 24)}</h2>
                <div className="banner_description">
                    <h4>{cutshort(movies.overview, 280)}</h4>
                </div>
                <div className="banner_btn">
                    <button className="play"><PlayArrowIcon/> Play</button>
                    <button className="info">More Info</button>
                </div>
            </div>
        <div className="banner_shadow"></div>
        </section>
    </>
  )
}

export default Banner